# Generated by Django 3.1.1 on 2020-09-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200910_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='pic',
        ),
    ]
