# Generated by Django 3.1.1 on 2020-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_picture_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
