# Generated by Django 3.1.2 on 2020-10-09 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_picture_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='weigth',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='picture',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='articles.article'),
        ),
    ]
