# Generated by Django 3.1.1 on 2020-09-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='publicUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(default='slug', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
    ]
